function(g4_enable_sanitizers target)
  if(NOT G4_ENABLE_SANITIZERS)
    return()
  endif()
  if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(${target} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-fsanitize=address,undefined;-fno-omit-frame-pointer>)
    target_link_options(${target} PRIVATE -fsanitize=address,undefined)
  else()
    message(WARNING "G4_ENABLE_SANITIZERS is unsupported by ${CMAKE_CXX_COMPILER_ID}")
  endif()
endfunction()

